const HERO_ABILITIES = {
  abaddon: ['./abilities/abaddon_aphotic_shield_hp1.png', './abilities/abaddon_borrowed_time_hp1.png', './abilities/abaddon_death_coil_hp1.png', './abilities/abaddon_frostmourne_hp1.png'],
  alchemist: ['./abilities/alchemist_acid_spray_hp1.png', './abilities/alchemist_chemical_rage_hp1.png', './abilities/alchemist_goblins_greed_hp1.png', './abilities/alchemist_unstable_concoction_hp1.png'],
  ancient_apparition: ['./abilities/ancient_apparition_chilling_touch_hp1.png', './abilities/ancient_apparition_cold_feet_hp1.png', './abilities/ancient_apparition_ice_blast_hp1.png', './abilities/ancient_apparition_ice_vortex_hp1.png'],
  antimage: ['./abilities/antimage_blink_hp1.png', './abilities/antimage_mana_break_hp1.png', './abilities/antimage_mana_void_hp1.png', './abilities/antimage_spell_shield_hp1.png'],
  axe: ['./abilities/axe_battle_hunger_hp1.png', './abilities/axe_berserkers_call_hp1.png', './abilities/axe_counter_helix_hp1.png', './abilities/axe_culling_blade_hp1.png'],
  bane: ['./abilities/bane_brain_sap_hp1.png', './abilities/bane_enfeeble_hp1.png', './abilities/bane_fiends_grip_hp1.png', './abilities/bane_nightmare_hp1.png'],
  batrider: ['./abilities/batrider_firefly_hp1.png', './abilities/batrider_flamebreak_hp1.png', './abilities/batrider_flaming_lasso_hp1.png', './abilities/batrider_sticky_napalm_hp1.png'],
  beastmaster: ['./abilities/beastmaster_call_of_the_wild_hp1.png', './abilities/beastmaster_inner_beast_hp1.png', './abilities/beastmaster_primal_roar_hp1.png', './abilities/beastmaster_wild_axes_hp1.png'],
  bloodseeker: ['./abilities/bloodseeker_bloodrage_hp1.png', './abilities/bloodseeker_blood_bath_hp1.png', './abilities/bloodseeker_rupture_hp1.png', './abilities/bloodseeker_thirst_hp1.png'],
  bounty_hunter: ['./abilities/bounty_hunter_jinada_hp1.png', './abilities/bounty_hunter_shuriken_toss_hp1.png', './abilities/bounty_hunter_track_hp1.png', './abilities/bounty_hunter_wind_walk_hp1.png'],
  brewmaster: ['./abilities/brewmaster_drunken_brawler_hp1.png', './abilities/brewmaster_drunken_haze_hp1.png', './abilities/brewmaster_primal_split_hp1.png', './abilities/brewmaster_thunder_clap_hp1.png'],
  bristleback: ['./abilities/bristleback_bristleback_hp1.png', './abilities/bristleback_quill_spray_hp1.png', './abilities/bristleback_viscous_nasal_goo_hp1.png', './abilities/bristleback_warpath_hp1.png'],
  broodmother: ['./abilities/broodmother_incapacitating_bite_hp1.png', './abilities/broodmother_insatiable_hunger_hp1.png', './abilities/broodmother_spawn_spiderlings_hp1.png', './abilities/broodmother_spin_web_hp1.png'],
  centaur: ['./abilities/centaur_double_edge_hp1.png', './abilities/centaur_hoof_stomp_hp1.png', './abilities/centaur_return_hp1.png', './abilities/centaur_stampede_hp1.png'],
  chaos_knight: ['./abilities/chaos_knight_chaos_bolt_hp1.png', './abilities/chaos_knight_chaos_strike_hp1.png', './abilities/chaos_knight_phantasm_hp1.png', './abilities/chaos_knight_reality_rift_hp1.png'],
  chen: ['./abilities/chen_hand_of_god_hp1.png', './abilities/chen_holy_persuasion_hp1.png', './abilities/chen_penitence_hp1.png', './abilities/chen_test_of_faith_hp1.png'],
  clinkz: ['./abilities/clinkz_death_pact_hp1.png', './abilities/clinkz_searing_arrows_hp1.png', './abilities/clinkz_strafe_hp1.png', './abilities/clinkz_wind_walk_hp1.png'],
  crystal_maiden: ['./abilities/crystal_maiden_brilliance_aura_hp1.png', './abilities/crystal_maiden_crystal_nova_hp1.png', './abilities/crystal_maiden_freezing_field_hp1.png', './abilities/crystal_maiden_frostbite_hp1.png'],
  dark_seer: ['./abilities/dark_seer_ion_shell_hp1.png', './abilities/dark_seer_surge_hp1.png', './abilities/dark_seer_vacuum_hp1.png', './abilities/dark_seer_wall_of_replica_hp1.png'],
  dazzle: ['./abilities/dazzle_poison_touch_hp1.png', './abilities/dazzle_shadow_wave_hp1.png', './abilities/dazzle_shallow_grave_hp1.png', './abilities/dazzle_weave_hp1.png'],
  death_prophet: ['./abilities/death_prophet_carrion_swarm_hp1.png', './abilities/death_prophet_exorcism_hp1.png', './abilities/death_prophet_silence_hp1.png', './abilities/death_prophet_witchcraft_hp1.png'],
  disruptor: ['./abilities/disruptor_glimpse_hp1.png', './abilities/disruptor_kinetic_field_hp1.png', './abilities/disruptor_static_storm_hp1.png', './abilities/disruptor_thunder_strike_hp1.png'],
  doom_bringer: ['./abilities/doom_bringer_devour_hp1.png', './abilities/doom_bringer_doom_hp1.png', './abilities/doom_bringer_lvl_death_hp1.png', './abilities/doom_bringer_scorched_earth_hp1.png'],
  dragon_knight: ['./abilities/dragon_knight_breathe_fire_hp1.png', './abilities/dragon_knight_dragon_blood_hp1.png', './abilities/dragon_knight_dragon_tail_hp1.png', './abilities/dragon_knight_elder_dragon_form_hp1.png'],
  drow_ranger: ['./abilities/drow_ranger_frost_arrows_hp1.png', './abilities/drow_ranger_marksmanship_hp1.png', './abilities/drow_ranger_trueshot_hp1.png', './abilities/drow_ranger_wave_of_silence_hp1.png'],
  earth_spirit: ['./abilities/earth_spirit_boulder_smash_hp1.png', './abilities/earth_spirit_geomagnetic_grip_hp1.png', './abilities/earth_spirit_magnetize_hp1.png', './abilities/earth_spirit_rolling_boulder_hp1.png', './abilities/earth_spirit_stone_caller_hp1.png'],
  earthshaker: ['./abilities/earthshaker_aftershock_hp1.png', './abilities/earthshaker_echo_slam_hp1.png', './abilities/earthshaker_enchant_totem_hp1.png', './abilities/earthshaker_fissure_hp1.png'],
  elder_titan: ['./abilities/elder_titan_ancestral_spirit_hp1.png', './abilities/elder_titan_earth_splitter_hp1.png', './abilities/elder_titan_echo_stomp_hp1.png', './abilities/elder_titan_natural_order_hp1.png'],
  ember_spirit: ['./abilities/ember_spirit_activate_fire_remnant_hp1.png', './abilities/ember_spirit_flame_guard_hp1.png', './abilities/ember_spirit_searing_chains_hp1.png', './abilities/ember_spirit_sleight_of_fist_hp1.png'],
  enchantress: ['./abilities/enchantress_enchant_hp1.png', './abilities/enchantress_impetus_hp1.png', './abilities/enchantress_natures_attendants_hp1.png', './abilities/enchantress_untouchable_hp1.png'],
  enigma: ['./abilities/enigma_black_hole_hp1.png', './abilities/enigma_demonic_conversion_hp1.png', './abilities/enigma_malefice_hp1.png', './abilities/enigma_midnight_pulse_hp1.png'],
  faceless_void: ['./abilities/faceless_void_backtrack_hp1.png', './abilities/faceless_void_chronosphere_hp1.png', './abilities/faceless_void_time_lock_hp1.png', './abilities/faceless_void_time_walk_hp1.png'],
  furion: ['./abilities/furion_force_of_nature_hp1.png', './abilities/furion_sprout_hp1.png', './abilities/furion_teleportation_hp1.png', './abilities/furion_wrath_of_nature_hp1.png'],
  gyrocopter: ['./abilities/gyrocopter_call_down_hp1.png', './abilities/gyrocopter_flak_cannon_hp1.png', './abilities/gyrocopter_homing_missile_hp1.png', './abilities/gyrocopter_rocket_barrage_hp1.png'],
  huskar: ['./abilities/huskar_berserkers_blood_hp1.png', './abilities/huskar_burning_spear_hp1.png', './abilities/huskar_inner_vitality_hp1.png', './abilities/huskar_life_break_hp1.png'],
  invoker: ['./abilities/invoker_alacrity_hp1.png', './abilities/invoker_chaos_meteor_hp1.png', './abilities/invoker_cold_snap_hp1.png', './abilities/invoker_deafening_blast_hp1.png', './abilities/invoker_emp_hp1.png', './abilities/invoker_forge_spirit_hp1.png', './abilities/invoker_ghost_walk_hp1.png', './abilities/invoker_ice_wall_hp1.png', './abilities/invoker_invoke_hp1.png', './abilities/invoker_sun_strike_hp1.png', './abilities/invoker_tornado_hp1.png'],
  jakiro: ['./abilities/jakiro_dual_breath_hp1.png', './abilities/jakiro_ice_path_hp1.png', './abilities/jakiro_liquid_fire_hp1.png', './abilities/jakiro_macropyre_hp1.png'],
  juggernaut: ['./abilities/juggernaut_blade_dance_hp1.png', './abilities/juggernaut_blade_fury_hp1.png', './abilities/juggernaut_healing_ward_hp1.png', './abilities/juggernaut_omni_slash_hp1.png'],
  keeper_of_the_light: ['./abilities/keeper_of_the_light_blinding_light_hp1.png', './abilities/keeper_of_the_light_chakra_magic_hp1.png', './abilities/keeper_of_the_light_illuminate_hp1.png', './abilities/keeper_of_the_light_mana_leak_hp1.png', './abilities/keeper_of_the_light_spirit_form_hp1.png'],
  kunkka: ['./abilities/kunkka_ghostship_hp1.png', './abilities/kunkka_tidebringer_hp1.png', './abilities/kunkka_torrent_hp1.png', './abilities/kunkka_x_marks_the_spot_hp1.png'],
  legion_commander: ['./abilities/legion_commander_duel_hp1.png', './abilities/legion_commander_moment_of_courage_hp1.png', './abilities/legion_commander_overwhelming_odds_hp1.png', './abilities/legion_commander_press_the_attack_hp1.png'],
  leshrac: ['./abilities/leshrac_diabolic_edict_hp1.png', './abilities/leshrac_lightning_storm_hp1.png', './abilities/leshrac_pulse_nova_hp1.png', './abilities/leshrac_split_earth_hp1.png'],
  lich: ['./abilities/lich_chain_frost_hp1.png', './abilities/lich_dark_ritual_hp1.png', './abilities/lich_frost_armor_hp1.png', './abilities/lich_frost_nova_hp1.png'],
  life_stealer: ['./abilities/life_stealer_consume_hp1.png', './abilities/life_stealer_feast_hp1.png', './abilities/life_stealer_infest_hp1.png', './abilities/life_stealer_open_wounds_hp1.png', './abilities/life_stealer_rage_hp1.png'],
  lina: ['./abilities/lina_dragon_slave_hp1.png', './abilities/lina_fiery_soul_hp1.png', './abilities/lina_laguna_blade_hp1.png', './abilities/lina_light_strike_array_hp1.png'],
  lion: ['./abilities/lion_finger_of_death_hp1.png', './abilities/lion_impale_hp1.png', './abilities/lion_mana_drain_hp1.png', './abilities/lion_voodoo_hp1.png'],
  lone_druid: ['./abilities/lone_druid_rabid_hp1.png', './abilities/lone_druid_spirit_bear_hp1.png', './abilities/lone_druid_synergy_hp1.png', './abilities/lone_druid_true_form_hp1.png'],
  luna: ['./abilities/luna_eclipse_hp1.png', './abilities/luna_lucent_beam_hp1.png', './abilities/luna_lunar_blessing_hp1.png', './abilities/luna_moon_glaive_hp1.png'],
  lycan: ['./abilities/lycan_feral_impulse_hp1.png', './abilities/lycan_howl_hp1.png', './abilities/lycan_shapeshift_hp1.png', './abilities/lycan_summon_wolves_hp1.png'],
  magnataur: ['./abilities/magnataur_empower_hp1.png', './abilities/magnataur_reverse_polarity_hp1.png', './abilities/magnataur_shockwave_hp1.png', './abilities/magnataur_skewer_hp1.png'],
  medusa: ['./abilities/medusa_mana_shield_hp1.png', './abilities/medusa_mystic_snake_hp1.png', './abilities/medusa_split_shot_hp1.png', './abilities/medusa_stone_gaze_hp1.png'],
  meepo: ['./abilities/meepo_divided_we_stand_hp1.png', './abilities/meepo_earthbind_hp1.png', './abilities/meepo_geostrike_hp1.png', './abilities/meepo_poof_hp1.png'],
  mirana: ['./abilities/mirana_arrow_hp1.png', './abilities/mirana_invis_hp1.png', './abilities/mirana_leap_hp1.png', './abilities/mirana_starfall_hp1.png'],
  morphling: ['./abilities/morphling_adaptive_strike_hp1.png', './abilities/morphling_morph_agi_hp1.png', './abilities/morphling_replicate_hp1.png', './abilities/morphling_waveform_hp1.png'],
  naga_siren: ['./abilities/naga_siren_ensnare_hp1.png', './abilities/naga_siren_mirror_image_hp1.png', './abilities/naga_siren_rip_tide_hp1.png', './abilities/naga_siren_song_of_the_siren_hp1.png'],
  necrolyte: ['./abilities/necrolyte_death_pulse_hp1.png', './abilities/necrolyte_heartstopper_aura_hp1.png', './abilities/necrolyte_reapers_scythe_hp1.png', './abilities/necrolyte_sadist_hp1.png'],
  nevermore: ['./abilities/nevermore_dark_lord_hp1.png', './abilities/nevermore_necromastery_hp1.png', './abilities/nevermore_requiem_hp1.png', './abilities/nevermore_shadowraze1_hp1.png'],
  night_stalker: ['./abilities/night_stalker_crippling_fear_hp1.png', './abilities/night_stalker_darkness_hp1.png', './abilities/night_stalker_hunter_in_the_night_hp1.png', './abilities/night_stalker_void_hp1.png'],
  nyx_assassin: ['./abilities/nyx_assassin_impale_hp1.png', './abilities/nyx_assassin_mana_burn_hp1.png', './abilities/nyx_assassin_spiked_carapace_hp1.png', './abilities/nyx_assassin_vendetta_hp1.png'],
  obsidian_destroyer: ['./abilities/obsidian_destroyer_arcane_orb_hp1.png', './abilities/obsidian_destroyer_astral_imprisonment_hp1.png', './abilities/obsidian_destroyer_essence_aura_hp1.png', './abilities/obsidian_destroyer_sanity_eclipse_hp1.png'],
  ogre_magi: ['./abilities/ogre_magi_bloodlust_hp1.png', './abilities/ogre_magi_fireblast_hp1.png', './abilities/ogre_magi_ignite_hp1.png', './abilities/ogre_magi_multicast_hp1.png'],
  omniknight: ['./abilities/omniknight_degen_aura_hp1.png', './abilities/omniknight_guardian_angel_hp1.png', './abilities/omniknight_purification_hp1.png', './abilities/omniknight_repel_hp1.png'],
  phantom_assassin: ['./abilities/phantom_assassin_blur_hp1.png', './abilities/phantom_assassin_coup_de_grace_hp1.png', './abilities/phantom_assassin_phantom_strike_hp1.png', './abilities/phantom_assassin_stifling_dagger_hp1.png'],
  phantom_lancer: ['./abilities/phantom_lancer_doppelwalk_hp1.png', './abilities/phantom_lancer_juxtapose_hp1.png', './abilities/phantom_lancer_phantom_edge_hp1.png', './abilities/phantom_lancer_spirit_lance_hp1.png'],
  phoenix: ['./abilities/phoenix_fire_spirits_hp1.png', './abilities/phoenix_icarus_dive_hp1.png', './abilities/phoenix_sun_ray_hp1.png', './abilities/phoenix_supernova_hp1.png'],
  puck: ['./abilities/puck_dream_coil_hp1.png', './abilities/puck_ethereal_jaunt_hp1.png', './abilities/puck_illusory_orb_hp1.png', './abilities/puck_phase_shift_hp1.png', './abilities/puck_waning_rift_hp1.png'],
  pudge: ['./abilities/pudge_dismember_hp1.png', './abilities/pudge_flesh_heap_hp1.png', './abilities/pudge_meat_hook_hp1.png', './abilities/pudge_rot_hp1.png'],
  pugna: ['./abilities/pugna_decrepify_hp1.png', './abilities/pugna_life_drain_hp1.png', './abilities/pugna_nether_blast_hp1.png', './abilities/pugna_nether_ward_hp1.png'],
  queenofpain: ['./abilities/queenofpain_blink_hp1.png', './abilities/queenofpain_scream_of_pain_hp1.png', './abilities/queenofpain_shadow_strike_hp1.png', './abilities/queenofpain_sonic_wave_hp1.png'],
  rattletrap: ['./abilities/rattletrap_battery_assault_hp1.png', './abilities/rattletrap_hookshot_hp1.png', './abilities/rattletrap_power_cogs_hp1.png', './abilities/rattletrap_rocket_flare_hp1.png'],
  razor: ['./abilities/razor_eye_of_the_storm_hp1.png', './abilities/razor_plasma_field_hp1.png', './abilities/razor_static_link_hp1.png', './abilities/razor_unstable_current_hp1.png'],
  riki: ['./abilities/riki_backstab_hp1.png', './abilities/riki_blink_strike_hp1.png', './abilities/riki_permanent_invisibility_hp1.png', './abilities/riki_smoke_screen_hp1.png'],
  rubick: ['./abilities/rubick_fade_bolt_hp1.png', './abilities/rubick_null_field_hp1.png', './abilities/rubick_spell_steal_hp1.png', './abilities/rubick_telekinesis_hp1.png'],
  sandking: ['./abilities/sandking_burrowstrike_hp1.png', './abilities/sandking_caustic_finale_hp1.png', './abilities/sandking_epicenter_hp1.png', './abilities/sandking_sand_storm_hp1.png'],
  shadow_demon: ['./abilities/shadow_demon_demonic_purge_hp1.png', './abilities/shadow_demon_disruption_hp1.png', './abilities/shadow_demon_shadow_poison_hp1.png', './abilities/shadow_demon_soul_catcher_hp1.png'],
  shadow_shaman: ['./abilities/shadow_shaman_ether_shock_hp1.png', './abilities/shadow_shaman_mass_serpent_ward_hp1.png', './abilities/shadow_shaman_shackles_hp1.png', './abilities/shadow_shaman_voodoo_hp1.png'],
  shredder: ['./abilities/shredder_chakram_hp1.png', './abilities/shredder_reactive_armor_hp1.png', './abilities/shredder_timber_chain_hp1.png', './abilities/shredder_whirling_death_hp1.png'],
  silencer: ['./abilities/silencer_curse_of_the_silent_hp1.png', './abilities/silencer_glaives_of_wisdom_hp1.png', './abilities/silencer_global_silence_hp1.png', './abilities/silencer_last_word_hp1.png'],
  skeleton_king: ['./abilities/skeleton_king_hellfire_blast_hp1.png', './abilities/skeleton_king_mortal_strike_hp1.png', './abilities/skeleton_king_reincarnation_hp1.png', './abilities/skeleton_king_vampiric_aura_hp1.png'],
  skywrath_mage: ['./abilities/skywrath_mage_ancient_seal_hp1.png', './abilities/skywrath_mage_arcane_bolt_hp1.png', './abilities/skywrath_mage_concussive_shot_hp1.png', './abilities/skywrath_mage_mystic_flare_hp1.png'],
  slardar: ['./abilities/slardar_amplify_damage_hp1.png', './abilities/slardar_bash_hp1.png', './abilities/slardar_slithereen_crush_hp1.png', './abilities/slardar_sprint_hp1.png'],
  slark: ['./abilities/slark_dark_pact_hp1.png', './abilities/slark_essence_shift_hp1.png', './abilities/slark_pounce_hp1.png', './abilities/slark_shadow_dance_hp1.png'],
  sniper: ['./abilities/sniper_assassinate_hp1.png', './abilities/sniper_headshot_hp1.png', './abilities/sniper_shrapnel_hp1.png', './abilities/sniper_take_aim_hp1.png'],
  spectre: ['./abilities/spectre_desolate_hp1.png', './abilities/spectre_dispersion_hp1.png', './abilities/spectre_haunt_hp1.png', './abilities/spectre_reality_hp1.png', './abilities/spectre_spectral_dagger_hp1.png'],
  spirit_breaker: ['./abilities/spirit_breaker_charge_of_darkness_hp1.png', './abilities/spirit_breaker_empowering_haste_hp1.png', './abilities/spirit_breaker_greater_bash_hp1.png', './abilities/spirit_breaker_nether_strike_hp1.png'],
  storm_spirit: ['./abilities/storm_spirit_ball_lightning_hp1.png', './abilities/storm_spirit_electric_vortex_hp1.png', './abilities/storm_spirit_overload_hp1.png', './abilities/storm_spirit_static_remnant_hp1.png'],
  sven: ['./abilities/sven_gods_strength_hp1.png', './abilities/sven_great_cleave_hp1.png', './abilities/sven_storm_bolt_hp1.png', './abilities/sven_warcry_hp1.png'],
  templar_assassin: ['./abilities/templar_assassin_meld_hp1.png', './abilities/templar_assassin_psionic_trap_hp1.png', './abilities/templar_assassin_psi_blades_hp1.png', './abilities/templar_assassin_refraction_hp1.png'],
  terrorblade: ['./abilities/terrorblade_conjure_image_hp1.png', './abilities/terrorblade_metamorphosis_hp1.png', './abilities/terrorblade_reflection_hp1.png', './abilities/terrorblade_sunder_hp1.png'],
  tidehunter: ['./abilities/tidehunter_anchor_smash_hp1.png', './abilities/tidehunter_gush_hp1.png', './abilities/tidehunter_kraken_shell_hp1.png', './abilities/tidehunter_ravage_hp1.png'],
  tinker: ['./abilities/tinker_heat_seeking_missile_hp1.png', './abilities/tinker_laser_hp1.png', './abilities/tinker_march_of_the_machines_hp1.png', './abilities/tinker_rearm_hp1.png'],
  tiny: ['./abilities/tiny_avalanche_hp1.png', './abilities/tiny_craggy_exterior_hp1.png', './abilities/tiny_grow_hp1.png', './abilities/tiny_toss_hp1.png'],
  treant: ['./abilities/treant_leech_seed_hp1.png', './abilities/treant_living_armor_hp1.png', './abilities/treant_natures_guise_hp1.png', './abilities/treant_overgrowth_hp1.png'],
  troll_warlord: ['./abilities/troll_warlord_battle_trance_hp1.png', './abilities/troll_warlord_berserkers_rage_hp1.png', './abilities/troll_warlord_fervor_hp1.png', './abilities/troll_warlord_whirling_axes_ranged_hp1.png'],
  tusk: ['./abilities/tusk_frozen_sigil_hp1.png', './abilities/tusk_ice_shards_hp1.png', './abilities/tusk_snowball_hp1.png', './abilities/tusk_walrus_punch_hp1.png'],
  undying: ['./abilities/undying_decay_hp1.png', './abilities/undying_flesh_golem_hp1.png', './abilities/undying_soul_rip_hp1.png', './abilities/undying_tombstone_hp1.png'],
  ursa: ['./abilities/ursa_earthshock_hp1.png', './abilities/ursa_enrage_hp1.png', './abilities/ursa_fury_swipes_hp1.png', './abilities/ursa_overpower_hp1.png'],
  vengefulspirit: ['./abilities/vengefulspirit_command_aura_hp1.png', './abilities/vengefulspirit_magic_missile_hp1.png', './abilities/vengefulspirit_nether_swap_hp1.png', './abilities/vengefulspirit_wave_of_terror_hp1.png'],
  venomancer: ['./abilities/venomancer_plague_ward_hp1.png', './abilities/venomancer_poison_nova_hp1.png', './abilities/venomancer_poison_sting_hp1.png', './abilities/venomancer_venomous_gale_hp1.png'],
  viper: ['./abilities/viper_corrosive_skin_hp1.png', './abilities/viper_nethertoxin_hp1.png', './abilities/viper_poison_attack_hp1.png', './abilities/viper_viper_strike_hp1.png'],
  visage: ['./abilities/visage_gravekeepers_cloak_hp1.png', './abilities/visage_grave_chill_hp1.png', './abilities/visage_soul_assumption_hp1.png', './abilities/visage_summon_familiars_hp1.png'],
  warlock: ['./abilities/warlock_fatal_bonds_hp1.png', './abilities/warlock_rain_of_chaos_hp1.png', './abilities/warlock_shadow_word_hp1.png', './abilities/warlock_upheaval_hp1.png'],
  weaver: ['./abilities/weaver_geminate_attack_hp1.png', './abilities/weaver_shukuchi_hp1.png', './abilities/weaver_the_swarm_hp1.png', './abilities/weaver_time_lapse_hp1.png'],
  windrunner: ['./abilities/windrunner_focusfire_hp1.png', './abilities/windrunner_powershot_hp1.png', './abilities/windrunner_shackleshot_hp1.png', './abilities/windrunner_windrun_hp1.png'],
  wisp: ['./abilities/wisp_overcharge_hp1.png', './abilities/wisp_relocate_hp1.png', './abilities/wisp_spirits_hp1.png', './abilities/wisp_tether_hp1.png'],
  witch_doctor: ['./abilities/witch_doctor_death_ward_hp1.png', './abilities/witch_doctor_maledict_hp1.png', './abilities/witch_doctor_paralyzing_cask_hp1.png', './abilities/witch_doctor_voodoo_restoration_hp1.png'],
  zuus: ['./abilities/zuus_arc_lightning_hp1.png', './abilities/zuus_lightning_bolt_hp1.png', './abilities/zuus_static_field_hp1.png', './abilities/zuus_thundergods_wrath_hp1.png'],
};

function getHeroAbilities(key) {
  return HERO_ABILITIES[key] || [];
}