// ══════════════════════════════════════════════════════
// HERO MEDIA MAP — gif/mp4 если есть, иначе png
// Папка с медиа: ./videos/
// ══════════════════════════════════════════════════════

const HERO_MEDIA = {
  // ── GIF ──────────────────────────────────────────
  antimage:           { type: 'gif', file: './videos/antimage.gif' },
  axe:                { type: 'gif', file: './videos/axe.gif' },
  bloodseeker:        { type: 'gif', file: './videos/bloodseeker.gif' },
  crystal_maiden:     { type: 'gif', file: './videos/crystalmaiden.gif' },
  drow_ranger:        { type: 'gif', file: './videos/drowranger.gif' },
  juggernaut:         { type: 'mp4', file: './videos/juggernout.mp4' },
  mirana:             { type: 'gif', file: './videos/mirana.gif' },
  morphling:          { type: 'gif', file: './videos/morphling.gif' },
  nevermore:          { type: 'gif', file: './videos/shadowfiend.gif' },
  phantom_lancer:     { type: 'gif', file: './videos/phantomlancer.gif' },
  razor:              { type: 'gif', file: './videos/razor.gif' },
  sand_king:          { type: 'mp4', file: './videos/sandking.mp4' },
  storm_spirit:       { type: 'gif', file: './videos/stormspirit.gif' },
  sven:               { type: 'gif', file: './videos/sven.gif' },
  tiny:               { type: 'gif', file: './videos/tiny.gif' },
  vengefulspirit:     { type: 'gif', file: './videos/vengefulspirit.gif' },
  windrunner:         { type: 'mp4', file: './videos/windranger.mp4' },
  zuus:               { type: 'gif', file: './videos/zeus.gif' },
  kunkka:             { type: 'gif', file: './videos/kunkka.gif' },
  lina:               { type: 'gif', file: './videos/lina.gif' },
  lion:               { type: 'mp4', file: './videos/lion.mp4' },
  shadow_shaman:      { type: 'gif', file: './videos/shadowshaman.gif' },
  slardar:            { type: 'gif', file: './videos/slardar.gif' },
  tidehunter:         { type: 'gif', file: './videos/tidehunter.gif' },
  witch_doctor:       { type: 'gif', file: './videos/witchdoctor.gif' },
  lich:               { type: 'mp4', file: './videos/lich.mp4' },
  riki:               { type: 'gif', file: './videos/riki.gif' },
  enigma:             { type: 'gif', file: './videos/enigma.gif' },
  tinker:             { type: 'gif', file: './videos/tinker.gif' },
  sniper:             { type: 'mp4', file: './videos/sniper.mp4' },
  necrolyte:          { type: 'gif', file: './videos/necrophos.gif' },
  warlock:            { type: 'gif', file: './videos/warlock.gif' },
  beastmaster:        { type: 'gif', file: './videos/beastmaster.gif' },
  queenofpain:        { type: 'gif', file: './videos/queenofpain.gif' },
  venomancer:         { type: 'mp4', file: './videos/venomancer.mp4' },
  faceless_void:      { type: 'gif', file: './videos/facelessvoid.gif' },
  skeleton_king:      { type: 'gif', file: './videos/wraithking.gif' },
  death_prophet:      { type: 'gif', file: './videos/deatch_prophet.gif' },
  phantom_assassin:   { type: 'gif', file: './videos/phantomassasin.gif' },
  pugna:              { type: 'gif', file: './videos/pugna.gif' },
  templar_assassin:   { type: 'mp4', file: './videos/templarassasin.mp4' },
  viper:              { type: 'gif', file: './videos/viper.gif' },
  luna:               { type: 'mp4', file: './videos/luna.mp4' },
  dragon_knight:      { type: 'gif', file: './videos/dragonknight.gif' },
  dazzle:             { type: 'gif', file: './videos/dazzle.gif' },
  rattletrap:         { type: 'gif', file: './videos/clockwerk.gif' },
  leshrac:            { type: 'mp4', file: './videos/leshrak.mp4' },
  furion:             { type: 'gif', file: './videos/naturesprophet.gif' },
  life_stealer:       { type: 'gif', file: './videos/lifestealer.gif' },
  dark_seer:          { type: 'gif', file: './videos/darkseer.gif' },
  clinkz:             { type: 'gif', file: './videos/clinkz.gif' },
  omniknight:         { type: 'gif', file: './videos/omniknight.gif' },
  enchantress:        { type: 'gif', file: './videos/enchantress.gif' },
  huskar:             { type: 'gif', file: './videos/huskar.gif' },
  night_stalker:      { type: 'gif', file: './videos/nightstalker.gif' },
  broodmother:        { type: 'gif', file: './videos/broodmother.gif' },
  bounty_hunter:      { type: 'mp4', file: './videos/bountyhunter.mp4' },
  weaver:             { type: 'gif', file: './videos/weaver.gif' },
  jakiro:             { type: 'gif', file: './videos/jakiro.gif' },
  batrider:           { type: 'gif', file: './videos/batrider.gif' },
  chen:               { type: 'gif', file: './videos/chen.gif' },
  spectre:            { type: 'mp4', file: './videos/spectre.mp4' },
  ancient_apparition: { type: 'gif', file: './videos/ancient.gif' },
  doom_bringer:       { type: 'gif', file: './videos/doom.gif' },
  ursa:               { type: 'gif', file: './videos/ursa.gif' },
  spirit_breaker:     { type: 'gif', file: './videos/spiritbreaker.gif' },
  gyrocopter:         { type: 'mp4', file: './videos/gyrocopter.mp4' },
  alchemist:          { type: 'gif', file: './videos/alchimist.gif' },
  invoker:            { type: 'gif', file: './videos/invoker.gif' },
  silencer:           { type: 'gif', file: './videos/silencer.gif' },
  obsidian_destroyer: { type: 'mp4', file: './videos/outworlddevouwer.mp4' },
  lycan:              { type: 'gif', file: './videos/lycan.gif' },
  brewmaster:         { type: 'gif', file: './videos/brewmaster.gif' },
  shadow_demon:       { type: 'mp4', file: './videos/shadowdemon.mp4' },
  lone_druid:         { type: 'mp4', file: './videos/lonedruid.mp4' },
  chaos_knight:       { type: 'gif', file: './videos/chaosknight.gif' },
  treant:             { type: 'mp4', file: './videos/trentprotector.mp4' },
  ogre_magi:          { type: 'gif', file: './videos/ogremagi.gif' },
  undying:            { type: 'gif', file: './videos/undying.gif' },
  rubick:             { type: 'gif', file: './videos/rubik.gif' },
  nyx_assassin:       { type: 'mp4', file: './videos/nyx.mp4' },
  naga_siren:         { type: 'gif', file: './videos/nagasieren.gif' },
  keeper_of_the_light:{ type: 'mp4', file: './videos/keeper_of_the_light.mp4' },
  wisp:               { type: 'gif', file: './videos/io.gif' },
  visage:             { type: 'gif', file: './videos/visage.gif' },
  slark:              { type: 'gif', file: './videos/slark.gif' },
  centaur:            { type: 'mp4', file: './videos/centour.mp4' },
  magnataur:          { type: 'mp4', file: './videos/magnus.mp4' },
  bristleback:        { type: 'gif', file: './videos/bristleback.gif' },
  tusk:               { type: 'mp4', file: './videos/tusk.mp4' },
  skywrath_mage:      { type: 'gif', file: './videos/skymage.gif' },
  abaddon:            { type: 'gif', file: './videos/abbadon.gif' },
  elder_titan:        { type: 'gif', file: './videos/eldertitan.gif' },
  legion_commander:   { type: 'gif', file: './videos/legioncommander.gif' },
  techies:            { type: 'mp4', file: './videos/techies.mp4' },
  ember_spirit:       { type: 'gif', file: './videos/emberspirit.gif' },
  earth_spirit:       { type: 'gif', file: './videos/earthspirit.gif' },
  terrorblade:        { type: 'gif', file: './videos/terrorblade.gif' },
  phoenix:            { type: 'gif', file: './videos/phoenix.gif' },
  oracle:             { type: 'mp4', file: './videos/oracle.mp4' },
  winter_wyvern:      { type: 'mp4', file: './videos/winterwyvern.mp4' },
  bane:               { type: 'mp4', file: './videos/bane.mp4' },
  earthshaker:        { type: 'mp4', file: './videos/earthshaker.mp4' },
  puck:               { type: 'mp4', file: './videos/puck.mp4' },
  pudge:              { type: 'mp4', file: './videos/pudge.mp4' },

  // ── БЕЗ МЕДИА — только png ──────────────────────
  // meepo, disruptor, medusa, troll_warlord, shredder (Timbersaw),
  // abyssal_underlord, arc_warden, monkey_king, dark_willow,
  // pangolier, grimstroke, hoodwink, void_spirit, snapfire,
  // mars, dawnbreaker, marci, primal_beast, muerta, ringmaster, kez
};

// ══════════════════════════════════════════════════════
// Хелпер: возвращает { type, file } или null (→ png)
// ══════════════════════════════════════════════════════
function getHeroMedia(key) {
  return HERO_MEDIA[key] || null;
}
