const HEROES = [
  {id:1,  name:"Anti-Mage",          key:"antimage",           attribute:"agility",      attack_type:"melee"},
  {id:2,  name:"Axe",                key:"axe",                attribute:"strength",     attack_type:"melee"},
  {id:3,  name:"Bane",               key:"bane",               attribute:"universal",    attack_type:"ranged"},
  {id:4,  name:"Bloodseeker",        key:"bloodseeker",        attribute:"agility",      attack_type:"melee"},
  {id:5,  name:"Crystal Maiden",     key:"crystal_maiden",     attribute:"intelligence", attack_type:"ranged"},
  {id:6,  name:"Drow Ranger",        key:"drow_ranger",        attribute:"agility",      attack_type:"ranged"},
  {id:7,  name:"Earthshaker",        key:"earthshaker",        attribute:"strength",     attack_type:"melee"},
  {id:8,  name:"Juggernaut",         key:"juggernaut",         attribute:"agility",      attack_type:"melee"},
  {id:9,  name:"Mirana",             key:"mirana",             attribute:"agility",      attack_type:"ranged"},
  {id:10, name:"Morphling",          key:"morphling",          attribute:"agility",      attack_type:"ranged"},
  {id:11, name:"Shadow Fiend",       key:"nevermore",          attribute:"agility",      attack_type:"ranged"},
  {id:12, name:"Phantom Lancer",     key:"phantom_lancer",     attribute:"agility",      attack_type:"melee"},
  {id:13, name:"Puck",               key:"puck",               attribute:"intelligence", attack_type:"ranged"},
  {id:14, name:"Pudge",              key:"pudge",              attribute:"strength",     attack_type:"melee"},
  {id:15, name:"Razor",              key:"razor",              attribute:"agility",      attack_type:"ranged"},
  {id:16, name:"Sand King",          key:"sand_king",          attribute:"universal",    attack_type:"melee"},
  {id:17, name:"Storm Spirit",       key:"storm_spirit",       attribute:"intelligence", attack_type:"ranged"},
  {id:18, name:"Sven",               key:"sven",               attribute:"strength",     attack_type:"melee"},
  {id:19, name:"Tiny",               key:"tiny",               attribute:"strength",     attack_type:"melee"},
  {id:20, name:"Vengeful Spirit",    key:"vengefulspirit",     attribute:"agility",      attack_type:"ranged"},
  {id:21, name:"Windranger",         key:"windrunner",         attribute:"universal",    attack_type:"ranged"},
  {id:22, name:"Zeus",               key:"zuus",               attribute:"intelligence", attack_type:"ranged"},
  {id:23, name:"Kunkka",             key:"kunkka",             attribute:"strength",     attack_type:"melee"},
  {id:24, name:"Lina",               key:"lina",               attribute:"intelligence", attack_type:"ranged"},
  {id:25, name:"Lion",               key:"lion",               attribute:"intelligence", attack_type:"ranged"},
  {id:26, name:"Shadow Shaman",      key:"shadow_shaman",      attribute:"intelligence", attack_type:"ranged"},
  {id:27, name:"Slardar",            key:"slardar",            attribute:"strength",     attack_type:"melee"},
  {id:28, name:"Tidehunter",         key:"tidehunter",         attribute:"strength",     attack_type:"melee"},
  {id:29, name:"Witch Doctor",       key:"witch_doctor",       attribute:"intelligence", attack_type:"ranged"},
  {id:30, name:"Lich",               key:"lich",               attribute:"intelligence", attack_type:"ranged"},
  {id:31, name:"Riki",               key:"riki",               attribute:"agility",      attack_type:"melee"},
  {id:32, name:"Enigma",             key:"enigma",             attribute:"universal",    attack_type:"ranged"},
  {id:33, name:"Tinker",             key:"tinker",             attribute:"intelligence", attack_type:"ranged"},
  {id:34, name:"Sniper",             key:"sniper",             attribute:"agility",      attack_type:"ranged"},
  {id:35, name:"Necrophos",          key:"necrolyte",          attribute:"intelligence", attack_type:"ranged"},
  {id:36, name:"Warlock",            key:"warlock",            attribute:"intelligence", attack_type:"ranged"},
  {id:37, name:"Beastmaster",        key:"beastmaster",        attribute:"universal",    attack_type:"melee"},
  {id:38, name:"Queen of Pain",      key:"queenofpain",        attribute:"intelligence", attack_type:"ranged"},
  {id:39, name:"Venomancer",         key:"venomancer",         attribute:"universal",    attack_type:"ranged"},
  {id:40, name:"Faceless Void",      key:"faceless_void",      attribute:"agility",      attack_type:"melee"},
  {id:41, name:"Wraith King",        key:"skeleton_king",      attribute:"strength",     attack_type:"melee"},
  {id:42, name:"Death Prophet",      key:"death_prophet",      attribute:"universal",    attack_type:"ranged"},
  {id:43, name:"Phantom Assassin",   key:"phantom_assassin",   attribute:"agility",      attack_type:"melee"},
  {id:44, name:"Pugna",              key:"pugna",              attribute:"intelligence", attack_type:"ranged"},
  {id:45, name:"Templar Assassin",   key:"templar_assassin",   attribute:"agility",      attack_type:"ranged"},
  {id:46, name:"Viper",              key:"viper",              attribute:"agility",      attack_type:"ranged"},
  {id:47, name:"Luna",               key:"luna",               attribute:"agility",      attack_type:"ranged"},
  {id:48, name:"Dragon Knight",      key:"dragon_knight",      attribute:"strength",     attack_type:"melee"},
  {id:49, name:"Dazzle",             key:"dazzle",             attribute:"universal",    attack_type:"ranged"},
  {id:50, name:"Clockwerk",          key:"rattletrap",         attribute:"strength",     attack_type:"melee"},
  {id:51, name:"Leshrac",            key:"leshrac",            attribute:"intelligence", attack_type:"ranged"},
  {id:52, name:"Nature's Prophet",   key:"furion",             attribute:"universal",    attack_type:"ranged"},
  {id:53, name:"Lifestealer",        key:"life_stealer",       attribute:"strength",     attack_type:"melee"},
  {id:54, name:"Dark Seer",          key:"dark_seer",          attribute:"intelligence", attack_type:"melee"},
  {id:55, name:"Clinkz",             key:"clinkz",             attribute:"agility",      attack_type:"ranged"},
  {id:56, name:"Omniknight",         key:"omniknight",         attribute:"strength",     attack_type:"melee"},
  {id:57, name:"Enchantress",        key:"enchantress",        attribute:"intelligence", attack_type:"ranged"},
  {id:58, name:"Huskar",             key:"huskar",             attribute:"strength",     attack_type:"ranged"},
  {id:59, name:"Night Stalker",      key:"night_stalker",      attribute:"strength",     attack_type:"melee"},
  {id:60, name:"Broodmother",        key:"broodmother",        attribute:"agility",      attack_type:"melee"},
  {id:61, name:"Bounty Hunter",      key:"bounty_hunter",      attribute:"agility",      attack_type:"melee"},
  {id:62, name:"Weaver",             key:"weaver",             attribute:"agility",      attack_type:"ranged"},
  {id:63, name:"Jakiro",             key:"jakiro",             attribute:"intelligence", attack_type:"ranged"},
  {id:64, name:"Batrider",           key:"batrider",           attribute:"universal",    attack_type:"ranged"},
  {id:65, name:"Chen",               key:"chen",               attribute:"intelligence", attack_type:"ranged"},
  {id:66, name:"Spectre",            key:"spectre",            attribute:"universal",    attack_type:"melee"},
  {id:67, name:"Ancient Apparition", key:"ancient_apparition", attribute:"intelligence", attack_type:"ranged"},
  {id:68, name:"Doom",               key:"doom_bringer",       attribute:"strength",     attack_type:"melee"},
  {id:69, name:"Ursa",               key:"ursa",               attribute:"agility",      attack_type:"melee"},
  {id:70, name:"Spirit Breaker",     key:"spirit_breaker",     attribute:"strength",     attack_type:"melee"},
  {id:71, name:"Gyrocopter",         key:"gyrocopter",         attribute:"agility",      attack_type:"ranged"},
  {id:72, name:"Alchemist",          key:"alchemist",          attribute:"strength",     attack_type:"melee"},
  {id:73, name:"Invoker",            key:"invoker",            attribute:"intelligence", attack_type:"ranged"},
  {id:74, name:"Silencer",           key:"silencer",           attribute:"intelligence", attack_type:"ranged"},
  {id:75, name:"Outworld Destroyer", key:"obsidian_destroyer", attribute:"intelligence", attack_type:"ranged"},
  {id:76, name:"Lycan",              key:"lycan",              attribute:"strength",     attack_type:"melee"},
  {id:77, name:"Brewmaster",         key:"brewmaster",         attribute:"universal",    attack_type:"melee"},
  {id:78, name:"Shadow Demon",       key:"shadow_demon",       attribute:"intelligence", attack_type:"ranged"},
  {id:79, name:"Lone Druid",         key:"lone_druid",         attribute:"agility",      attack_type:"ranged"},
  {id:80, name:"Chaos Knight",       key:"chaos_knight",       attribute:"strength",     attack_type:"melee"},
  {id:81, name:"Meepo",              key:"meepo",              attribute:"agility",      attack_type:"melee"},
  {id:82, name:"Treant Protector",   key:"treant",             attribute:"strength",     attack_type:"melee"},
  {id:83, name:"Ogre Magi",          key:"ogre_magi",          attribute:"strength",     attack_type:"melee"},
  {id:84, name:"Undying",            key:"undying",            attribute:"strength",     attack_type:"melee"},
  {id:85, name:"Rubick",             key:"rubick",             attribute:"intelligence", attack_type:"ranged"},
  {id:86, name:"Disruptor",          key:"disruptor",          attribute:"intelligence", attack_type:"ranged"},
  {id:87, name:"Nyx Assassin",       key:"nyx_assassin",       attribute:"universal",    attack_type:"melee"},
  {id:88, name:"Naga Siren",         key:"naga_siren",         attribute:"agility",      attack_type:"melee"},
  {id:89, name:"Keeper of the Light",key:"keeper_of_the_light",attribute:"intelligence", attack_type:"ranged"},
  {id:90, name:"Io",                 key:"wisp",               attribute:"universal",    attack_type:"ranged"},
  {id:91, name:"Visage",             key:"visage",             attribute:"universal",    attack_type:"ranged"},
  {id:92, name:"Slark",              key:"slark",              attribute:"agility",      attack_type:"melee"},
  {id:93, name:"Medusa",             key:"medusa",             attribute:"agility",      attack_type:"ranged"},
  {id:94, name:"Troll Warlord",      key:"troll_warlord",      attribute:"agility",      attack_type:"ranged"},
  {id:95, name:"Centaur Warrunner",  key:"centaur",            attribute:"strength",     attack_type:"melee"},
  {id:96, name:"Magnus",             key:"magnataur",          attribute:"universal",    attack_type:"melee"},
  {id:97, name:"Timbersaw",          key:"shredder",           attribute:"strength",     attack_type:"melee"},
  {id:98, name:"Bristleback",        key:"bristleback",        attribute:"strength",     attack_type:"melee"},
  {id:99, name:"Tusk",               key:"tusk",               attribute:"strength",     attack_type:"melee"},
  {id:100,name:"Skywrath Mage",      key:"skywrath_mage",      attribute:"intelligence", attack_type:"ranged"},
  {id:101,name:"Abaddon",            key:"abaddon",            attribute:"universal",    attack_type:"melee"},
  {id:102,name:"Elder Titan",        key:"elder_titan",        attribute:"strength",     attack_type:"melee"},
  {id:103,name:"Legion Commander",   key:"legion_commander",   attribute:"strength",     attack_type:"melee"},
  {id:104,name:"Techies",            key:"techies",            attribute:"universal",    attack_type:"ranged"},
  {id:105,name:"Ember Spirit",       key:"ember_spirit",       attribute:"agility",      attack_type:"melee"},
  {id:106,name:"Earth Spirit",       key:"earth_spirit",       attribute:"strength",     attack_type:"melee"},
  {id:107,name:"Underlord",          key:"abyssal_underlord",  attribute:"strength",     attack_type:"melee"},
  {id:108,name:"Terrorblade",        key:"terrorblade",        attribute:"agility",      attack_type:"melee"},
  {id:109,name:"Phoenix",            key:"phoenix",            attribute:"strength",     attack_type:"ranged"},
  {id:110,name:"Oracle",             key:"oracle",             attribute:"intelligence", attack_type:"ranged"},
  {id:111,name:"Winter Wyvern",      key:"winter_wyvern",      attribute:"intelligence", attack_type:"ranged"},
  {id:112,name:"Arc Warden",         key:"arc_warden",         attribute:"universal",    attack_type:"ranged"},
  {id:113,name:"Monkey King",        key:"monkey_king",        attribute:"agility",      attack_type:"melee"},
  {id:114,name:"Dark Willow",        key:"dark_willow",        attribute:"intelligence", attack_type:"ranged"},
  {id:115,name:"Pangolier",          key:"pangolier",          attribute:"universal",    attack_type:"melee"},
  {id:116,name:"Grimstroke",         key:"grimstroke",         attribute:"intelligence", attack_type:"ranged"},
  {id:117,name:"Hoodwink",           key:"hoodwink",           attribute:"agility",      attack_type:"ranged"},
  {id:118,name:"Void Spirit",        key:"void_spirit",        attribute:"universal",    attack_type:"melee"},
  {id:119,name:"Snapfire",           key:"snapfire",           attribute:"universal",    attack_type:"ranged"},
  {id:120,name:"Mars",               key:"mars",               attribute:"strength",     attack_type:"ranged"},
  {id:121,name:"Dawnbreaker",        key:"dawnbreaker",        attribute:"strength",     attack_type:"melee"},
  {id:122,name:"Marci",              key:"marci",              attribute:"universal",    attack_type:"melee"},
  {id:123,name:"Primal Beast",       key:"primal_beast",       attribute:"strength",     attack_type:"melee"},
  {id:124,name:"Muerta",             key:"muerta",             attribute:"intelligence", attack_type:"ranged"},
  {id:125,name:"Ringmaster",         key:"ringmaster",         attribute:"intelligence", attack_type:"ranged"},
  {id:126,name:"Kez",                key:"kez",                attribute:"agility",      attack_type:"melee"},
];
